# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leisureactivities', '0003_placetovisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceToEat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_page', models.CharField(max_length=1000)),
                ('link_img', models.CharField(max_length=1000)),
            ],
        ),
    ]
