# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leisureactivities', '0008_auto_20170315_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='placetoeat',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='placetovisit',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
