# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_desc', models.CharField(max_length=500)),
                ('item_img', models.ImageField(upload_to='pictures')),
                ('item_costprice', models.CharField(max_length=50)),
                ('seller_name', models.CharField(max_length=50)),
                ('seller_room', models.CharField(max_length=20)),
                ('seller_hostel', models.CharField(max_length=30)),
                ('seller_contact', models.CharField(max_length=11)),
            ],
        ),
    ]
