# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellmodel',
            name='item_type',
            field=models.CharField(default='type', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellmodel',
            name='item_img',
            field=models.ImageField(upload_to='buysell/pictures'),
        ),
    ]
