# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0002_auto_20170324_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellmodel',
            name='item_img',
            field=models.ImageField(upload_to='../buysell/pictures'),
        ),
    ]
