# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0011_auto_20170325_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellmodel',
            name='user_name',
            field=models.CharField(default='vaibhav', max_length=100),
            preserve_default=False,
        ),
    ]
